GET http://localhost:3000/api/books

###

POST http://localhost:3000/api/books HTTP/1.1
content-type: application/json

{
    "title": "El principito",
    "author": "Pepito perez sosa",
    "isbn": "123-456-789-2",
    "publishedDate": "01-12-2000"
}
